// SubVANLauncher.idl : SubVANLauncher의 IDL 소스입니다.
//

// 이 파일은 MIDL 도구에 의해 처리되어
// 형식 라이브러리(SubVANLauncher.tlb) 및 마샬링 코드가 생성됩니다.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(689E52E9-388A-48A6-8BA9-7F5A202EFD05),
	version(1.0),
	helpstring("SubVANLauncher 1.0 형식 라이브러리")
]
library SubVANLauncherLib
{
	importlib("stdole2.tlb");
};
